### ISSUE TITLE
How do you access a packet symbolically in READ PROTOCOLs?

### ISSUE THREAD

**Issue by jhayes-apl** [OpenC3/openc3#124]
I have a custom protocol that adds sequence numbers to outgoing CCSDS packets and checks sequence numbers on incoming packets.  For outgoing packets, i.e., within write_packet, I can modify the packet "symbolically":
<PRE>
      id = packet.read("CCSDSAPID_ID")
      seq_no = seq_nos.next_seq(id)
      packet.write("CCSDSSEQCNT", seq_no)
</PRE>

However, I cannot do this for incoming packets, i.e., within read_packet.  If I do this:
<PRE>
      id = packet.read("CCSDSAPID_ID")
</PRE>
I get this error: "RuntimeError : Packet item ' CCSDSAPID_ID' does not exist".  The work-around is to access the packet as raw data:
<PRE>
      data = packet.buffer(false)
      header = data[0,4].unpack('S>S>') # 1st two 16-bit words of primary header
      id = header[0]&0xff
</PRE>

I assume the error is because the packet has not been "identified" yet.  Is there a way to identify the packet from the protocol code (read_packet)?

**Comment by steven-efsi** [comment]
ident_packet = System.telemetry.identify!(packet.buffer, [TARGET_NAME])

where TARGET_NAME is an array of possible targets you think the packet could be. If all your targets use ccsds, then you can pass nil here.

See https://www.rubydoc.info/gems/cosmos/Cosmos/Telemetry#identify!-instance_method

**Comment by jhayes-apl** [comment]
That is a useful web site; I wish I had known about it earlier.  I have been reading the source code to figure out how to use COSMOS/OpenC3.  For example, I found identify_and_define_packet used in ignore_packet_protocol.rb.:
<PRE>
    def read_packet(packet)
      # Need to make sure packet is identified and defined
      target_names = nil
      target_names = @interface.target_names if @interface
      identified_packet = System.telemetry.identify_and_define_packet(packet, target_names)
</PRE>
I copied this and it works for my problem.  Now, I am unsure which to use, identify_and_define_packet or identify!.

**Comment by jmthomas** [comment]
You should not use `identify!` because we use that to update the OpenC3 Current Value Table (CVT). Following the examples in ignore_packet_protocol and override_protocol is the best way forward.

Also you should be using https://www.rubydoc.info/gems/openc3/OpenC3 ... or clone the repo and search from there

**Comment by steven-efsi** [comment]
Thanks for the advice, JM. In my case, the packets are being generated by a ruby script (the cfdp engine) so it may make sense to use identify! in the read_packet method, and identify (no bang) in the write_packet method of the protocol. If  you think that this is wrong, I will change to use identify_and_define_packet. But, since they are coming from ruby-land and not openc3 command packets or telemetry from the target, I think it's ok.
